server:
  port: 30020


spring:
  datasource:
    url: jdbc:mysql://47.96.159.71:3306/oomall?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true # 耿佳南
    username: oomall
    password: oomallp@$$w0rd

    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 47.98.252.133
    port: 6379
    database: 0
    jedis:
      pool:
        max-idle: 8
        max-wait:
        min-idle: 0
    timeout: 5000
  application:
    name: orderService

mybatis:
  mapper-locations: classpath:wowomall.mapper/*Mapper.xml
  type-aliases-package: com.xmu.wowoto.wowomall.domain
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://47.96.159.71:8888/eureka/

wowomall:
  preDeductStock: 5