server:
  port: 30020


spring:
  datasource:
    url: jdbc:mysql://148.70.28.112:3306/wowomall?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: wowoto
    password: zqhlovekly
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 129.28.122.147
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 50
        max-wait: 3000
        max-idle: 20
        min-idle: 2
    timeout: 5000
  application:
    name: wowoto-eureka-client-orderService

mybatis:
  mapper-locations: classpath:wowomall.mapper/*Mapper.xml
  type-aliases-package: com.xmu.wowoto.wowomall.domain
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://10.30.27.96:8761/eureka/