server:
  port: 60002
spring:
  application:
    name: orderService
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.52.88.176:3306/DB1_8?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=GMT%2B8&characterEncoding=utf8
    username: user1_8
    password: ooad8
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  redis:
    host: 112.124.5.232
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）

wowomall:
  preDeductStock: 30

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://139.196.212.100:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 148.70.28.112
    non-secure-port: 60002
#    ip-address: 192.168.1.145